version: '3.8'

services:
  # Дополнительные настройки для локальной разработки
  backend:
    environment:
      - NODE_ENV=development
      - DB_SYNCHRONIZE=true
      - DB_LOGGING=true

  prometheus:
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'

  grafana:
    environment:
      - GF_USERS_ALLOW_SIGN_UP=false