global:
  scrape_interval: 15s
  evaluation_interval: 15s
alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093
rule_files:
  - 'rules/alerts.yml'

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: [ 'localhost:9090' ]

  - job_name: 'backend'
    static_configs:
      - targets: [ 'backend:3000' ]
    metrics_path: /api/metrics

  - job_name: 'docker'
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
    relabel_configs:
      - source_labels: [ __meta_docker_container_label_prometheus_scrape ]
        regex: 'true'
        action: keep
      - source_labels: [ __meta_docker_container_label_prometheus_port ]
        regex: '(.+)'
        target_label: __address__
        replacement: '${1}:${2}'
      - source_labels: [ __meta_docker_container_label_prometheus_path ]
        regex: '(.+)'
        target_label: __metrics_path__
        replacement: '${1}'

  - job_name: 'postgres'
    static_configs:
      - targets: [ 'postgres-exporter:9187' ]
    scrape_interval: 15s

  - job_name: 'cadvisor'
    static_configs:
      - targets: [ 'cadvisor:8080' ]
    scrape_interval: 15s

