apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    version: 1
    editable: false

  - name: Elasticsearch
    type: elasticsearch
    access: proxy
    url: http://elasticsearch:9200
    database: "[filebeat-*]"
    isDefault: false
    version: 1
    editable: false
    jsonData:
      esVersion: 7.0.0
      timeField: "@timestamp"